capi_return is NULL
Call-back cb_f_in_lsoda__user__routines failed.
0
Traceback (most recent call last):
  File "nonspatial_coupled.py", line 85, in <module>
    path,clock = chv(m1,T,pow(Np,-delta),'lsoda',0.)
  File "./../simulation.py", line 105, in chv
    tj.integrate(s1)
  File "//anaconda/lib/python3.5/site-packages/scipy/integrate/_ode.py", line 408, in integrate
    self.f_params, self.jac_params)
  File "//anaconda/lib/python3.5/site-packages/scipy/integrate/_ode.py", line 1209, in run
    y1, t, istate = self.runner(*args)
  File "./../simulation.py", line 81, in chv_f
    agg_rate = sum((e.rate for e in m.events_slow))+sample_rate
  File "./../simulation.py", line 81, in <genexpr>
    agg_rate = sum((e.rate for e in m.events_slow))+sample_rate
KeyboardInterrupt
